name: 16-Working With Environments

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: STAGING

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my-env-value: ${{ vars.TARGET_VAR || 'default_value' }}

    steps:
      - name: Echo vars
        run: |
          echo "My Repo variable : ${{ env.my-env-value }}"
          echo "My Environment branch : ${{ inputs.target-env }}"
          echo "My env variable : ${{ vars.TARGET_VAR }}"