name: 18-1-reusable-workflow

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build_status:
        description: The status of the build process
        value: ${{ jobs.deploy.outputs.build-status }}
      deploy_url:
        description: The deployed URL
        value: ${{ jobs.deploy.outputs.deploy-url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.build-status}}
      deploy-url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          echo "Building using directory ${{inputs.target-directory}}"
          echo "build-status=success" >> "$GITHUB_OUTPUT"

      - name: deploy
        id: deploy
        run: |
          echo "Deploying build artifacts"
          echo "url=http://ww.google.com" >> "$GITHUB_OUTPUT"
